"""Generates a self-contained Lua script that builds a Resolve timeline from
a Template -- no file reads, no `os.execute`, nothing beyond direct calls to
the Resolve Lua API.

Why this exists (see README for the full story): DaVinci Resolve's Lua
scripting environment has no working `io` library and no `os.execute` (nor
`bmd.readfile`/`writefile`/`execute` as a sanctioned replacement) -- verified
interactively in Resolve's own Console against a real Resolve 21 install. A
Lua script running inside Resolve therefore cannot read a template.json file
or shell out to Python itself. The fix is to flip who does the work: a plain
Python process (which has no such restriction) runs the whole analysis,
prepares every media/subtitle asset on disk via media_prep.py, and then
emits a Lua script with every value already baked in as a literal. The
generated script's only job is to call the Resolve API with those literals --
nothing it does requires file I/O or process execution.

All strings (paths, labels, subtitle text) are emitted using Lua's raw
long-bracket syntax (`[[...]]`, escalating to `[=[...]=]` etc. if the value
itself happens to contain a closing sequence) instead of quoted strings with
backslash escapes -- far less error-prone for Windows paths and arbitrary
user-facing text than hand-rolling escape sequences.
"""
from __future__ import annotations

from pathlib import Path
from typing import Union

from resolve_plugin.analysis.template_schema import ClipSlot, Gap, MusicSegment, Template, VoiceSegment
from resolve_plugin.media_prep import (
    PlaceholderClipCache,
    SilentAudioPlaceholderCache,
    seconds_to_frames,
    write_srt,
)

ON_SCREEN_TEXT_TRACK_NAME = "Testo a schermo"
DIALOGUE_TRACK_NAME = "Dialogo (trascrizione)"
VOICE_TRACK_NAME = "Voce"
MUSIC_TRACK_NAME = "Musica"
MARKER_COLOR = "Yellow"


def _lua_long_string(value: str) -> str:
    level = 0
    while ("]" + "=" * level + "]") in value:
        level += 1
    eq = "=" * level
    return f"[{eq}[{value}]{eq}]"


def _lua_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return _lua_long_string(str(value))


def _timeline_items(template: Template) -> list[Union[ClipSlot, Gap]]:
    items: list[Union[ClipSlot, Gap]] = [*template.clips, *template.gaps]
    return sorted(items, key=lambda item: (
        item.source_in_seconds if isinstance(item, ClipSlot) else item.start_seconds
    ))


def _audio_items(template: Template) -> list[tuple[bool, Union[VoiceSegment, MusicSegment]]]:
    items = [(True, v) for v in template.voice_segments] + [(False, m) for m in template.music_segments]
    return sorted(items, key=lambda pair: pair[1].start_seconds)


def _record_frame_expr(seconds: float, fps: float) -> str:
    """A Lua expression for an absolute recordFrame: timelineStartFrame
    (Timeline:GetStartFrame(), read once near the top of the generated
    script) plus this position's own offset from the start of the
    template, floored at 1 (never literal 0). recordFrame is an ABSOLUTE
    frame in Resolve's own internal clock, and real Resolve timelines start
    at timecode 01:00:00:00, not 00:00:00:00 -- a bare small value sits
    before the timeline's actual addressable start."""
    return f"timelineStartFrame + {max(1, seconds_to_frames(seconds, fps))}"


def generate_lua_script(template: Template, timeline_name: str, work_dir: Path) -> str:
    """Prepares every media/subtitle asset the timeline needs (writing files
    under work_dir via media_prep.py) and returns the full Lua source that
    will build the timeline when run inside Resolve."""
    work_dir.mkdir(parents=True, exist_ok=True)
    fps = template.fps

    lines: list[str] = []

    def emit(line: str = "") -> None:
        lines.append(line)

    emit(f"-- Auto-generated by Auto Template for \"{timeline_name}\" -- do not edit by hand.")
    emit("-- Re-run the Python build command to regenerate this file after re-analyzing the video.")
    emit("")
    emit("if not resolve then")
    emit('  print("[Auto Template] Errore: esegui questo script dal menu Script di Resolve.")')
    emit("  return")
    emit("end")
    emit("")
    emit("local projectManager = resolve:GetProjectManager()")
    emit("local project = projectManager:GetCurrentProject()")
    emit("if not project then")
    emit('  print("[Auto Template] Errore: nessun progetto aperto in Resolve.")')
    emit("  return")
    emit("end")
    emit("local mediaPool = project:GetMediaPool()")
    emit("")
    emit(f"local timeline = mediaPool:CreateEmptyTimeline({_lua_long_string(timeline_name)})")
    emit("if not timeline then")
    emit('  print("[Auto Template] Errore: creazione timeline fallita.")')
    emit("  return")
    emit("end")
    emit("project:SetCurrentTimeline(timeline)")
    # recordFrame is an ABSOLUTE frame number in Resolve's own internal
    # clock, not relative to the timeline's own visible start -- and
    # Resolve timelines conventionally start at timecode 01:00:00:00 (one
    # hour in), not 00:00:00:00. Every recordFrame value tried without this
    # offset (0, then 1, then batched) landed identically wrong on a real
    # Resolve install, always falling back to end-of-timeline placement --
    # consistent with small values like 0/1 being before the timeline's
    # actual addressable start and getting rejected/ignored. GetStartFrame()
    # is the documented way to read that offset at runtime instead of
    # hardcoding the 01:00:00:00 convention (which is configurable).
    emit("local timelineStartFrame = timeline:GetStartFrame()")
    emit("")
    emit(f"local sourceItems = mediaPool:ImportMedia({{ {_lua_long_string(template.source_video_path)} }})")
    emit("local sourceItem = sourceItems and sourceItems[1]")
    emit("if not sourceItem then")
    emit('  print("[Auto Template] Errore: import del video sorgente fallito.")')
    emit("  return")
    emit("end")
    emit("")

    # Subtitle tracks are built HERE, before anything else touches the
    # timeline -- deliberately. recordFrame never worked for this specific
    # kind of clip on a real Resolve install: every value and combination
    # tried (0, 1, offset by timelineStartFrame, batched or not) still
    # landed the caption text past the end of the timeline instead of at
    # its real position, even though the *exact same* recordFrame mechanism
    # (see the voice/music code further below) works correctly for normal
    # audio/video clips. The one placement that HAS worked reliably in every
    # test all session is a clip appended with no recordFrame at all while
    # the timeline is still completely empty -- it simply lands at frame 0.
    # Doing the subtitle import first (before any video/audio content
    # exists) exploits that, instead of fighting recordFrame for this media
    # type. The .srt file's own per-cue timestamps then take over from
    # frame 0, positioning each caption correctly relative to the video.
    def emit_subtitle_track(overlays, filename: str, track_name: str) -> None:
        srt_path = work_dir / filename
        if not write_srt(overlays, srt_path):
            return
        # NOT `timeline:ImportIntoTimeline(path, {insertAsSubtitle=true})`:
        # that option key isn't part of the documented API (ImportIntoTimeline
        # is for AAF/XML timeline files) and silently did nothing against a
        # real Resolve install. The mechanism that actually works -- same one
        # used by other open-source Resolve subtitle tools -- is to import the
        # .srt as its own MediaPoolItem, then AppendToTimeline it onto a
        # subtitle track exactly like any other clip.
        emit("do")
        emit(f"  local srtItems = mediaPool:ImportMedia({{ {_lua_long_string(str(srt_path))} }})")
        emit("  if srtItems and srtItems[1] then")
        emit('    timeline:AddTrack("subtitle")')
        emit('    local idx = timeline:GetTrackCount("subtitle")')
        emit(f"    timeline:SetTrackName(\"subtitle\", idx, {_lua_long_string(track_name)})")
        emit(
            "    local appended = mediaPool:AppendToTimeline({ { mediaPoolItem = srtItems[1], "
            "trackIndex = idx } })"
        )
        emit("    if appended and appended[1] then")
        emit(
            f'      print("[Auto Template] Traccia sottotitoli \\"{track_name}\\" importata: " .. '
            f"{_lua_long_string(str(srt_path))})"
        )
        emit("    else")
        emit(
            f'      print("[Auto Template] ATTENZIONE: import sottotitoli \\"{track_name}\\" fallito '
            '(AppendToTimeline non ha creato la clip). File: " .. '
            f"{_lua_long_string(str(srt_path))})"
        )
        emit("    end")
        emit("  else")
        emit(
            f'    print("[Auto Template] ATTENZIONE: ImportMedia del file .srt \\"{track_name}\\" '
            'fallito. File: " .. ' + f"{_lua_long_string(str(srt_path))})"
        )
        emit("  end")
        emit("end")
        emit("")

    emit_subtitle_track(template.texts, "on_screen_text.srt", ON_SCREEN_TEXT_TRACK_NAME)
    emit_subtitle_track(template.dialogue, "dialogue.srt", DIALOGUE_TRACK_NAME)

    # Every clip/gap on the main track gets an explicit recordFrame too, not
    # just voice/music -- otherwise it depends on plain sequential ordering
    # ("no recordFrame" lands at the end of whatever's already on the
    # timeline), which broke the moment the subtitle import above got
    # appended first: the main track's first clip then landed AFTER the
    # subtitle block instead of at the true start (confirmed on a real
    # Resolve install). An explicit absolute position makes every track
    # immune to what else was appended before or after it.
    placeholder_cache = PlaceholderClipCache(work_dir, fps)
    for item in _timeline_items(template):
        if isinstance(item, ClipSlot):
            record_frame = _record_frame_expr(item.timeline_start_seconds, fps)
            start_frame = seconds_to_frames(item.source_in_seconds, fps)
            end_frame = max(start_frame, seconds_to_frames(item.source_out_seconds, fps) - 1)
            emit(
                "local appended = mediaPool:AppendToTimeline({ "
                f"{{ mediaPoolItem = sourceItem, startFrame = {start_frame}, endFrame = {end_frame}, "
                f"recordFrame = {record_frame} }} }})"
            )
            if item.transforms:
                emit("if appended and appended[1] then")
                for transform in item.transforms:
                    for key, value in transform.properties.items():
                        emit(f"  appended[1]:SetProperty({_lua_long_string(key)}, {_lua_literal(value)})")
                emit("end")
            emit("")
        else:
            duration = item.end_seconds - item.start_seconds
            if duration <= 0:
                continue
            record_frame = _record_frame_expr(item.start_seconds, fps)
            placeholder_path, _ = placeholder_cache.get_or_create(duration)
            end_frame = max(0, seconds_to_frames(duration, fps) - 1)
            emit(f"local gapItems = mediaPool:ImportMedia({{ {_lua_long_string(str(placeholder_path))} }})")
            emit("if gapItems and gapItems[1] then")
            emit(
                "  mediaPool:AppendToTimeline({ "
                f"{{ mediaPoolItem = gapItems[1], startFrame = 0, endFrame = {end_frame}, "
                f"recordFrame = {record_frame} }} }})"
            )
            emit("end")
            emit("")

    for note in template.effect_notes:
        frame_id = seconds_to_frames(note.at_seconds, fps)
        label = note.label or "Detected effect"
        note_text = (
            f"Rilevato automaticamente ({note.source}, confidenza={note.confidence:.2f}). "
            "Applica manualmente l'effetto/transizione corrispondente qui."
        )
        emit(
            f"timeline:AddMarker({frame_id}, \"{MARKER_COLOR}\", "
            f"{_lua_long_string(label)}, {_lua_long_string(note_text)}, 1)"
        )
    if template.effect_notes:
        emit("")

    # Everything below that needs an explicit timeline position (voice,
    # music, their silence fillers) goes through its own separate
    # AppendToTimeline call, each with an explicit recordFrame -- NOT
    # batched into one shared call. A batched version was tried and tested
    # worse on a real Resolve install (items landed with garbled/merged
    # durations instead of their own precise ones) -- reverted so this fix
    # (the timelineStartFrame offset below) can be verified in isolation,
    # one change at a time. Unlike subtitles (built at the very top of this
    # function instead), recordFrame + timelineStartFrame DOES correctly
    # position normal audio/video clips like these -- confirmed on a real
    # Resolve install.
    if template.voice_segments or template.music_segments:
        silence_cache = SilentAudioPlaceholderCache(work_dir)
        emit('timeline:AddTrack("audio")')
        emit('local voiceTrackIndex = timeline:GetTrackCount("audio")')
        emit(f'timeline:SetTrackName("audio", voiceTrackIndex, {_lua_long_string(VOICE_TRACK_NAME)})')
        emit('timeline:AddTrack("audio")')
        emit('local musicTrackIndex = timeline:GetTrackCount("audio")')
        emit(f'timeline:SetTrackName("audio", musicTrackIndex, {_lua_long_string(MUSIC_TRACK_NAME)})')
        emit("")

        for is_voice, segment in _audio_items(template):
            duration = segment.end_seconds - segment.start_seconds
            if duration <= 0:
                continue
            real_track = "voiceTrackIndex" if is_voice else "musicTrackIndex"
            silent_track = "musicTrackIndex" if is_voice else "voiceTrackIndex"
            record_frame = _record_frame_expr(segment.start_seconds, fps)

            start_frame = seconds_to_frames(segment.start_seconds, fps)
            end_frame = max(start_frame, seconds_to_frames(segment.end_seconds, fps) - 1)
            emit(
                "mediaPool:AppendToTimeline({ { mediaPoolItem = sourceItem, "
                f"startFrame = {start_frame}, endFrame = {end_frame}, mediaType = 2, "
                f"trackIndex = {real_track}, recordFrame = {record_frame} }} }})"
            )

            silence_path, _ = silence_cache.get_or_create(duration)
            silence_end_frame = max(0, seconds_to_frames(duration, fps) - 1)
            emit(f"local silenceItems = mediaPool:ImportMedia({{ {_lua_long_string(str(silence_path))} }})")
            emit("if silenceItems and silenceItems[1] then")
            emit(
                "  mediaPool:AppendToTimeline({ { mediaPoolItem = silenceItems[1], startFrame = 0, "
                f"endFrame = {silence_end_frame}, trackIndex = {silent_track}, "
                f"recordFrame = {record_frame} }} }})"
            )
            emit("end")
            emit("")

    emit(f'print("[Auto Template] Timeline creata con successo: " .. {_lua_long_string(timeline_name)})')

    return "\n".join(lines) + "\n"
