"""Installs the Auto Template plugin into DaVinci Resolve's per-user Scripts
folder on Windows.

Run once (after `pip install -r requirements.txt`):

    python scripts/install.py

Re-run it after pulling code changes to refresh the copy Resolve actually
loads.

Why a separate "lib" copy instead of pointing Resolve straight at this repo:
Resolve's Scripts menu lists every .py file it finds under Scripts/<category>,
including in subfolders. If the whole `resolve_plugin` package (many
internal modules) sat directly in that folder, every module would show up
as its own bogus menu entry. So we copy the package to a private location
and drop a single generated launcher script where Resolve actually looks.

Which category folder: older Resolve versions had a generic "Utility"
category; Resolve 21 dropped it in favor of page-named categories only
(Comp/Edit/Color/Deliver -- confirmed against a real Resolve 21 install).
We use "Edit" since that's where an editing-timeline tool belongs and it's
guaranteed to exist as a category in current Resolve versions.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_SRC = REPO_ROOT / "resolve_plugin"

APPDATA = Path(os.environ.get("APPDATA", str(Path.home())))
LIB_INSTALL_DIR = APPDATA / "AutoTemplatePlugin"
FUSION_SCRIPTS_DIR = APPDATA / "Blackmagic Design" / "DaVinci Resolve" / "Support" / "Fusion" / "Scripts"
SCRIPTS_EDIT_DIR = FUSION_SCRIPTS_DIR / "Edit"
# Older installs (or older Resolve versions) may have put the launcher here;
# clean it up so there's never a stale duplicate entry in the Scripts menu.
LEGACY_SCRIPTS_UTILITY_DIR = FUSION_SCRIPTS_DIR / "Utility"
LAUNCHER_NAME = "Auto Template.py"

LAUNCHER_TEMPLATE = '''"""Auto-generated by scripts/install.py -- do not edit by hand.

Launches the Auto Template plugin. Re-run scripts/install.py after changing
plugin code to refresh the copy Resolve actually loads.
"""
import sys
sys.path.insert(0, r"{lib_dir}")
from resolve_plugin.entry import main
main(bmd)
'''


def install() -> None:
    if sys.platform != "win32":
        print(
            "This installer targets Windows (Resolve Free on Windows).\n"
            "On other platforms, copy resolve_plugin/ somewhere on disk and "
            "create an equivalent launcher under your Resolve "
            "Fusion/Scripts/Edit folder by hand."
        )

    LIB_INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    dest_package_dir = LIB_INSTALL_DIR / "resolve_plugin"
    if dest_package_dir.exists():
        shutil.rmtree(dest_package_dir)
    shutil.copytree(PACKAGE_SRC, dest_package_dir)
    print(f"Copied plugin code to: {dest_package_dir}")

    legacy_launcher = LEGACY_SCRIPTS_UTILITY_DIR / LAUNCHER_NAME
    if legacy_launcher.exists():
        legacy_launcher.unlink()
        print(f"Removed stale launcher from: {legacy_launcher}")

    SCRIPTS_EDIT_DIR.mkdir(parents=True, exist_ok=True)
    launcher_path = SCRIPTS_EDIT_DIR / LAUNCHER_NAME
    launcher_path.write_text(
        LAUNCHER_TEMPLATE.format(lib_dir=str(LIB_INSTALL_DIR)), encoding="utf-8"
    )
    print(f"Installed launcher at: {launcher_path}")
    print(
        "\nDone. Restart DaVinci Resolve (or reopen the Scripts menu) and look "
        "for Workspace > Scripts > Edit > Auto Template."
    )


if __name__ == "__main__":
    install()
