"""Installs the Auto Template plugin into DaVinci Resolve's per-user Scripts
folder on Windows.

Run once (after `pip install -r requirements.txt`):

    python scripts/install.py

Re-run it after pulling code changes to refresh the copy Resolve actually
loads.

Why Lua instead of Python for the Scripts-menu entry: DaVinci Resolve 21.1
moved Scripts-menu Python execution to Resolve Studio only -- on the Free
edition, .py files no longer show up under Workspace > Scripts at all. Lua
scripting is unrestricted on both editions, so the Resolve-facing part of
this plugin (lua/Auto Template.lua) is Lua; it shells out to a plain Python
process (via the generated run_analysis.py bootstrap) for the AI analysis,
which never touches the Resolve API and so isn't affected by the
restriction either way.

Why a separate "lib" copy instead of pointing Resolve straight at this repo:
Resolve's Scripts menu lists every script file it finds under
Scripts/<category>, including in subfolders. If the whole `resolve_plugin`
package (many internal modules) sat directly in that folder, every module
would show up as its own bogus menu entry. So we copy the package to a
private location and drop a single generated launcher script where Resolve
actually looks.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_SRC = REPO_ROOT / "resolve_plugin"
LUA_TEMPLATE_SRC = REPO_ROOT / "lua" / "Auto Template.lua"

APPDATA = Path(os.environ.get("APPDATA", str(Path.home())))
LIB_INSTALL_DIR = APPDATA / "AutoTemplatePlugin"
PROJECTS_ROOT = Path.home() / "AutoTemplateProjects"
FUSION_SCRIPTS_DIR = APPDATA / "Blackmagic Design" / "DaVinci Resolve" / "Support" / "Fusion" / "Scripts"
SCRIPTS_EDIT_DIR = FUSION_SCRIPTS_DIR / "Edit"
# Older installs may have left a (now non-functional on Free 21.1+) Python
# launcher behind; clean it up so there's never a stale/duplicate entry.
LEGACY_SCRIPTS_UTILITY_DIR = FUSION_SCRIPTS_DIR / "Utility"
LAUNCHER_BASENAME = "Auto Template"

RUN_ANALYSIS_TEMPLATE = '''"""Auto-generated by scripts/install.py -- do not edit by hand.

Bootstraps resolve_plugin onto sys.path and runs the CLI analysis entry
point. Called by lua/Auto Template.lua via a plain subprocess -- this file
never touches the Resolve API, so Resolve's Python-scripting restriction on
the Free edition doesn't apply to it.
"""
import sys
sys.path.insert(0, r"{lib_dir}")
from resolve_plugin.analyze_cli import main
sys.exit(main(sys.argv[1:]))
'''


def _lua_string_literal(value: str) -> str:
    """Escapes a plain string for embedding inside a Lua double-quoted
    string literal (mainly: backslashes in Windows paths)."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def install() -> None:
    if sys.platform != "win32":
        print(
            "This installer targets Windows (Resolve on Windows).\n"
            "On other platforms, copy resolve_plugin/ somewhere on disk and "
            "adapt lua/Auto Template.lua's placeholders and install location "
            "by hand."
        )

    LIB_INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    dest_package_dir = LIB_INSTALL_DIR / "resolve_plugin"
    if dest_package_dir.exists():
        shutil.rmtree(dest_package_dir)
    shutil.copytree(PACKAGE_SRC, dest_package_dir)
    print(f"Copied plugin code to: {dest_package_dir}")

    run_analysis_path = LIB_INSTALL_DIR / "run_analysis.py"
    run_analysis_path.write_text(
        RUN_ANALYSIS_TEMPLATE.format(lib_dir=str(LIB_INSTALL_DIR)), encoding="utf-8"
    )
    print(f"Wrote analysis bootstrap to: {run_analysis_path}")

    PROJECTS_ROOT.mkdir(parents=True, exist_ok=True)

    lua_source = LUA_TEMPLATE_SRC.read_text(encoding="utf-8")
    lua_source = (
        lua_source.replace("__PYTHON_EXE__", _lua_string_literal("python"))
        .replace("__LIB_DIR__", _lua_string_literal(str(LIB_INSTALL_DIR)))
        .replace("__PROJECTS_ROOT__", _lua_string_literal(str(PROJECTS_ROOT)))
    )

    legacy_launcher = LEGACY_SCRIPTS_UTILITY_DIR / f"{LAUNCHER_BASENAME}.py"
    if legacy_launcher.exists():
        legacy_launcher.unlink()
        print(f"Removed stale launcher from: {legacy_launcher}")

    SCRIPTS_EDIT_DIR.mkdir(parents=True, exist_ok=True)
    old_python_launcher = SCRIPTS_EDIT_DIR / f"{LAUNCHER_BASENAME}.py"
    if old_python_launcher.exists():
        old_python_launcher.unlink()
        print(f"Removed stale launcher from: {old_python_launcher}")

    lua_launcher_path = SCRIPTS_EDIT_DIR / f"{LAUNCHER_BASENAME}.lua"
    lua_launcher_path.write_text(lua_source, encoding="utf-8")
    print(f"Installed launcher at: {lua_launcher_path}")

    print(
        "\nDone. Restart DaVinci Resolve (or reopen the Scripts menu) and look "
        "for Workspace > Scripts > Edit > Auto Template."
    )


if __name__ == "__main__":
    install()
