"""Installs the Auto Template plugin's Python side on Windows.

Run once (after `pip install -r requirements.txt`):

    python scripts/install.py

Re-run it after pulling code changes to refresh the copy that
`run_build.py` (and therefore every future `python ... build_project`
invocation) uses.

Why there is no Resolve Scripts-menu launcher installed anymore: DaVinci
Resolve's Lua scripting environment (Console and Scripts-menu alike) has no
working `io` library and no `os.execute` -- confirmed interactively against
a real Resolve 21 install (see README). A script running inside Resolve
therefore cannot read a file or launch an external process, so it cannot
itself drive the Python analysis or even read back its result. The fix:
`resolve_plugin.build_project` is a plain Python process (run by you, from a
terminal, no Resolve involved yet) that does the analysis AND writes a
ready-to-run Lua script -- with every value already baked in as a literal --
directly into Resolve's own Scripts/Edit folder. Each analyzed video gets
its own script there, e.g. "Auto Template - my_video_20260916_143000.lua";
open it from Workspace > Scripts > Edit after running the build command.

Why a separate "lib" copy instead of running straight from this repo
checkout: keeps `run_build.py` working even if you later move or delete the
cloned repo folder.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_SRC = REPO_ROOT / "resolve_plugin"

APPDATA = Path(os.environ.get("APPDATA", str(Path.home())))
LIB_INSTALL_DIR = APPDATA / "AutoTemplatePlugin"
PROJECTS_ROOT = Path.home() / "AutoTemplateProjects"
FUSION_SCRIPTS_DIR = APPDATA / "Blackmagic Design" / "DaVinci Resolve" / "Support" / "Fusion" / "Scripts"
SCRIPTS_EDIT_DIR = FUSION_SCRIPTS_DIR / "Edit"
LEGACY_SCRIPTS_UTILITY_DIR = FUSION_SCRIPTS_DIR / "Utility"
LAUNCHER_BASENAME = "Auto Template"

RUN_BUILD_TEMPLATE = '''r"""Auto-generated by scripts/install.py -- do not edit by hand.

Bootstraps resolve_plugin onto sys.path and runs the "build a project"
command. Run this from a terminal with a video path as its one argument:

    python "{run_build_path}" "C:\\path\\to\\video.mp4"

It never touches the Resolve API -- see scripts/install.py's docstring for
why that's exactly the point.
"""
import sys
sys.path.insert(0, r"{lib_dir}")
from resolve_plugin.build_project import main
sys.exit(main(sys.argv[1:]))
'''


def _remove_if_exists(path: Path, label: str) -> None:
    if path.exists():
        path.unlink()
        print(f"Removed stale {label}: {path}")


def install() -> None:
    if sys.platform != "win32":
        print(
            "This installer targets Windows (Resolve on Windows).\n"
            "On other platforms, copy resolve_plugin/ somewhere on disk and "
            "run `python -m resolve_plugin.build_project <video>` directly "
            "(adjust the Scripts/Edit path inside build_project.py for your OS)."
        )

    LIB_INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    dest_package_dir = LIB_INSTALL_DIR / "resolve_plugin"
    # Overwrite in place instead of rmtree()-ing first: deleting the old
    # copy tends to hit PermissionError on Windows when antivirus real-time
    # scanning has a file inside momentarily locked (observed in practice).
    # dirs_exist_ok=True merges the new tree over the old one without ever
    # needing to delete a directory.
    shutil.copytree(PACKAGE_SRC, dest_package_dir, dirs_exist_ok=True)
    print(f"Copied plugin code to: {dest_package_dir}")

    run_build_path = LIB_INSTALL_DIR / "run_build.py"
    run_build_path.write_text(
        RUN_BUILD_TEMPLATE.format(lib_dir=str(LIB_INSTALL_DIR), run_build_path=str(run_build_path)),
        encoding="utf-8",
    )
    print(f"Wrote build bootstrap to: {run_build_path}")

    PROJECTS_ROOT.mkdir(parents=True, exist_ok=True)

    # Clean up anything left behind by older versions of this installer:
    # a Python launcher in the now-nonexistent "Utility" category, a Python
    # launcher previously placed in "Edit", and the single static Lua
    # launcher from the short-lived runtime-JSON-parsing design -- all
    # superseded by the per-project generated scripts.
    _remove_if_exists(LEGACY_SCRIPTS_UTILITY_DIR / f"{LAUNCHER_BASENAME}.py", "launcher")
    _remove_if_exists(SCRIPTS_EDIT_DIR / f"{LAUNCHER_BASENAME}.py", "launcher")
    _remove_if_exists(SCRIPTS_EDIT_DIR / f"{LAUNCHER_BASENAME}.lua", "launcher")

    print(
        "\nDone. To build a timeline from a video, run:\n"
        f'    python "{run_build_path}" "C:\\path\\to\\your\\video.mp4"\n'
        "then in Resolve open Workspace > Scripts > Edit and run the "
        '"Auto Template - ..." entry it created.'
    )


if __name__ == "__main__":
    install()
